name = "ashen-depths"
main = "worker.js"
compatibility_date = "2026-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ashen-depths-db"
database_id = "a1bcd165-25e3-4ee2-a840-10a7937eb6b6"
